# An `osbuild-composer` blueprint for the Fedora workstation edition, based on
# the `ext/fedora-kickstarts/fedora-workstation-base.ks` file.

packages = [
    { name = "@workstation-product-environment" }
]
