# An `osbuild-composer` blueprint for the Fedora workstation edition, based on
# the `ext/fedora-kickstarts/fedora-live-workstation.ks` file.

# These packages are installed upon the 'base' fedora as defined in
# `osbuild-composer`.
packages = [
    { name = "@workstation-product-environment" }
]

# XXX, it'd be nicer if the desktop environment groups put this into an RPM.
# XXX, this is only applicable to the `live-installer` image type ...
customizations.files = [
    { path = "/etc/sysconfig/livesys", data = "livesys_session=\"gnome\"" }
]

# XXX, it'd be nicer if the desktop environment groups put this into an RPM.
# XXX, this is only applicable to the `live-installer` image type ...
customizations.services.enabled = ["livesys", "livesys-late"]
