# An `osbuild-composer` blueprint for the Fedora workstation edition, based on
# the `ext/fedora-kickstarts/fedora-workstation-base.ks` file.

packages = [
    { name = "@workstation-product-environment" }
]

# XXX, it'd be nicer if the desktop environment groups put this into an RPM.
customizations.files = [
    { path = "/etc/sysconfig/livesys", data = "livesys_session=\"gnome\"" }
]
