name = "fedora-cloud-disk-raw"

# XXX this is the experimental 'core' distro in osbuild-composer/images
distro = "fedora-core-39"

# These packages are installed upon the 'base' fedora as defined in
# `osbuild-composer`.

# XXX normally this removes kernel and adds kernel-core, removes firewalld
# XXX geolite databases should be removed
packages = [
    { name = "fedora-release-server" },
    { name = "@cloud-server-environment" },
    { name = "python3-dnf-plugin-tracer" },
    { name = "qemu-guest-agent" },
]

# XXX, it'd be nicer if the desktop environment groups put this into an RPM.
# XXX, this is only applicable to the `live-installer` image type ...
customizations.services.enabled = ["sshd", "cloud-init", "cloud-init-local", "cloud-config", "cloud-final"]
