# An `osbuild-composer` blueprint for the Fedora XFCE spin, based on
# the `ext/fedora-kickstarts/fedora-live-i3.ks` file.
name = "fedora-i3-live"

# XXX this is the experimental 'core' distro in osbuild-composer/images
distro = "fedora-core-39"

# These packages are installed upon the 'base' fedora as defined in
# `osbuild-composer`.

# XXX, it'd be nicer if the desktop environment groups put this into an RPM.
# XXX, for example an fedora-release-xfce-live that can depend on wget/these
# XXX, the other groups?
packages = [
    { name = "@i3-desktop-environment" },
    { name = "feh" },
    { name = "dex-autostart" },
    { name = "thunar" },
    { name = "gnome-keyring" },
    { name = "@admin-tools" },
    { name = "wget" },
    { name = "system-config-printer" }
]

# XXX, it'd be nicer if the desktop environment groups put this into an RPM.
customizations.files = [
    # XXX, this is only applicable to the `live-installer` image type ...
    { path = "/etc/sysconfig/livesys", data = "livesys_session=\"i3\"" },

    { path = "/etc/sysconfig/desktop", data = "PREFERRED=/usr/bin/i3\nDISPLAYMANAGER=/usr/bin/lightdm" }
]

# XXX, it'd be nicer if the desktop environment groups put this into an RPM.
# XXX, this is only applicable to the `live-installer` image type ...
customizations.services.enabled = ["livesys", "livesys-late"]
