# An `osbuild-composer` blueprint for the Fedora XFCE spin, based on
# the `ext/fedora-kickstarts/fedora-live-xfce.ks` file.
name = "fedora-xfce-live-iso"

# XXX this is the experimental 'ng' distro in osbuild-composer/images
distro = "fedora-ng-39"

# These packages are installed upon the 'base' fedora as defined in
# `osbuild-composer`.
packages = [
    # Desktop Environment
    { name = "fedora-release-xfce" },
    { name = "@xfce-desktop-environment" },
    { name = "@xfce-apps" },
    { name = "@xfce-extra-plugins" },
    { name = "@xfce-media" },
    { name = "@xfce-office" },
    { name = "wget" },
    { name = "system-config-printer" },

    # Install Environment
    { name = "anaconda" },
    { name = "anaconda-install-env-deps" },
    { name = "anaconda-live" },
    { name = "@anaconda-tools" },
    { name = "glibc-all-langpacks" },
]

customizations.files = [
    # XXX, this is only applicable to the `live-installer` image type ...
    { path = "/etc/sysconfig/livesys", data = "livesys_session=\"xfce\"" },

    { path = "/etc/sysconfig/desktop", data = "PREFERRED=/usr/bin/startxfce4\nDISPLAYMANAGER=/usr/bin/lightdm" }
]

customizations.services.enabled = ["livesys", "livesys-late"]
